# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True, verbose_name='\u0420\u0456\u043a')),
                ('month', models.IntegerField(null=True, verbose_name='\u041c\u0456\u0441\u044f\u0446\u044c')),
                ('day', models.IntegerField(null=True, verbose_name='\u0414\u0435\u043d\u044c')),
                ('visited', models.BooleanField(default=True, verbose_name='\u0412\u0456\u0434\u0432\u0456\u0434\u0430\u0432')),
                ('student_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0412\u0456\u0437\u0438\u0442',
                'verbose_name_plural': '\u0412\u0456\u0437\u0438\u0442\u0438',
            },
        ),
    ]
